package com.eric.sys.model;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USERID
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.FULLNAME
     *
     * @mbggenerated
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NICKNAME
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ISEXPIRED
     *
     * @mbggenerated
     */
    private Short isexpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ISLOCK
     *
     * @mbggenerated
     */
    private Short islock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PICTURE
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ORIGINAL_PICTURE
     *
     * @mbggenerated
     */
    private String originalPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.FROMTYPE
     *
     * @mbggenerated
     */
    private Short fromtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ACCOUNTTYPE
     *
     * @mbggenerated
     */
    private Integer accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.REF_TABLE
     *
     * @mbggenerated
     */
    private String refTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.REF_ID
     *
     * @mbggenerated
     */
    private Long refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.WEIXIN
     *
     * @mbggenerated
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.WEIXIN_USERID
     *
     * @mbggenerated
     */
    private Long weixinUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.WEIXIN_STATUS
     *
     * @mbggenerated
     */
    private Short weixinStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.IS_FIRST_LOGIN
     *
     * @mbggenerated
     */
    private Short isFirstLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.WELMSGSEND_STATUS
     *
     * @mbggenerated
     */
    private Integer welmsgsendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.MSGSEND_STATUS
     *
     * @mbggenerated
     */
    private Short msgsendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ENT_ID
     *
     * @mbggenerated
     */
    private Long entId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.WXENT_ID
     *
     * @mbggenerated
     */
    private Long wxentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.RECORD_STATUS
     *
     * @mbggenerated
     */
    private Integer recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USERID
     *
     * @return the value of sys_user.USERID
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USERID
     *
     * @param userid the value for sys_user.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.FULLNAME
     *
     * @return the value of sys_user.FULLNAME
     *
     * @mbggenerated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.FULLNAME
     *
     * @param fullname the value for sys_user.FULLNAME
     *
     * @mbggenerated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NICKNAME
     *
     * @return the value of sys_user.NICKNAME
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NICKNAME
     *
     * @param nickname the value for sys_user.NICKNAME
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ACCOUNT
     *
     * @return the value of sys_user.ACCOUNT
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ACCOUNT
     *
     * @param account the value for sys_user.ACCOUNT
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PASSWORD
     *
     * @return the value of sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PASSWORD
     *
     * @param password the value for sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ISEXPIRED
     *
     * @return the value of sys_user.ISEXPIRED
     *
     * @mbggenerated
     */
    public Short getIsexpired() {
        return isexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ISEXPIRED
     *
     * @param isexpired the value for sys_user.ISEXPIRED
     *
     * @mbggenerated
     */
    public void setIsexpired(Short isexpired) {
        this.isexpired = isexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ISLOCK
     *
     * @return the value of sys_user.ISLOCK
     *
     * @mbggenerated
     */
    public Short getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ISLOCK
     *
     * @param islock the value for sys_user.ISLOCK
     *
     * @mbggenerated
     */
    public void setIslock(Short islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATETIME
     *
     * @return the value of sys_user.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATETIME
     *
     * @param createtime the value for sys_user.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.STATUS
     *
     * @return the value of sys_user.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.STATUS
     *
     * @param status the value for sys_user.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EMAIL
     *
     * @return the value of sys_user.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EMAIL
     *
     * @param email the value for sys_user.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.MOBILE
     *
     * @return the value of sys_user.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.MOBILE
     *
     * @param mobile the value for sys_user.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHONE
     *
     * @return the value of sys_user.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHONE
     *
     * @param phone the value for sys_user.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.SEX
     *
     * @return the value of sys_user.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.SEX
     *
     * @param sex the value for sys_user.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PICTURE
     *
     * @return the value of sys_user.PICTURE
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PICTURE
     *
     * @param picture the value for sys_user.PICTURE
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ORIGINAL_PICTURE
     *
     * @return the value of sys_user.ORIGINAL_PICTURE
     *
     * @mbggenerated
     */
    public String getOriginalPicture() {
        return originalPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ORIGINAL_PICTURE
     *
     * @param originalPicture the value for sys_user.ORIGINAL_PICTURE
     *
     * @mbggenerated
     */
    public void setOriginalPicture(String originalPicture) {
        this.originalPicture = originalPicture == null ? null : originalPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.FROMTYPE
     *
     * @return the value of sys_user.FROMTYPE
     *
     * @mbggenerated
     */
    public Short getFromtype() {
        return fromtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.FROMTYPE
     *
     * @param fromtype the value for sys_user.FROMTYPE
     *
     * @mbggenerated
     */
    public void setFromtype(Short fromtype) {
        this.fromtype = fromtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ACCOUNTTYPE
     *
     * @return the value of sys_user.ACCOUNTTYPE
     *
     * @mbggenerated
     */
    public Integer getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ACCOUNTTYPE
     *
     * @param accounttype the value for sys_user.ACCOUNTTYPE
     *
     * @mbggenerated
     */
    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REF_TABLE
     *
     * @return the value of sys_user.REF_TABLE
     *
     * @mbggenerated
     */
    public String getRefTable() {
        return refTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REF_TABLE
     *
     * @param refTable the value for sys_user.REF_TABLE
     *
     * @mbggenerated
     */
    public void setRefTable(String refTable) {
        this.refTable = refTable == null ? null : refTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REF_ID
     *
     * @return the value of sys_user.REF_ID
     *
     * @mbggenerated
     */
    public Long getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REF_ID
     *
     * @param refId the value for sys_user.REF_ID
     *
     * @mbggenerated
     */
    public void setRefId(Long refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.WEIXIN
     *
     * @return the value of sys_user.WEIXIN
     *
     * @mbggenerated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.WEIXIN
     *
     * @param weixin the value for sys_user.WEIXIN
     *
     * @mbggenerated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.WEIXIN_USERID
     *
     * @return the value of sys_user.WEIXIN_USERID
     *
     * @mbggenerated
     */
    public Long getWeixinUserid() {
        return weixinUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.WEIXIN_USERID
     *
     * @param weixinUserid the value for sys_user.WEIXIN_USERID
     *
     * @mbggenerated
     */
    public void setWeixinUserid(Long weixinUserid) {
        this.weixinUserid = weixinUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.WEIXIN_STATUS
     *
     * @return the value of sys_user.WEIXIN_STATUS
     *
     * @mbggenerated
     */
    public Short getWeixinStatus() {
        return weixinStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.WEIXIN_STATUS
     *
     * @param weixinStatus the value for sys_user.WEIXIN_STATUS
     *
     * @mbggenerated
     */
    public void setWeixinStatus(Short weixinStatus) {
        this.weixinStatus = weixinStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.IS_FIRST_LOGIN
     *
     * @return the value of sys_user.IS_FIRST_LOGIN
     *
     * @mbggenerated
     */
    public Short getIsFirstLogin() {
        return isFirstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.IS_FIRST_LOGIN
     *
     * @param isFirstLogin the value for sys_user.IS_FIRST_LOGIN
     *
     * @mbggenerated
     */
    public void setIsFirstLogin(Short isFirstLogin) {
        this.isFirstLogin = isFirstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.WELMSGSEND_STATUS
     *
     * @return the value of sys_user.WELMSGSEND_STATUS
     *
     * @mbggenerated
     */
    public Integer getWelmsgsendStatus() {
        return welmsgsendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.WELMSGSEND_STATUS
     *
     * @param welmsgsendStatus the value for sys_user.WELMSGSEND_STATUS
     *
     * @mbggenerated
     */
    public void setWelmsgsendStatus(Integer welmsgsendStatus) {
        this.welmsgsendStatus = welmsgsendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.MSGSEND_STATUS
     *
     * @return the value of sys_user.MSGSEND_STATUS
     *
     * @mbggenerated
     */
    public Short getMsgsendStatus() {
        return msgsendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.MSGSEND_STATUS
     *
     * @param msgsendStatus the value for sys_user.MSGSEND_STATUS
     *
     * @mbggenerated
     */
    public void setMsgsendStatus(Short msgsendStatus) {
        this.msgsendStatus = msgsendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ENT_ID
     *
     * @return the value of sys_user.ENT_ID
     *
     * @mbggenerated
     */
    public Long getEntId() {
        return entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ENT_ID
     *
     * @param entId the value for sys_user.ENT_ID
     *
     * @mbggenerated
     */
    public void setEntId(Long entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.WXENT_ID
     *
     * @return the value of sys_user.WXENT_ID
     *
     * @mbggenerated
     */
    public Long getWxentId() {
        return wxentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.WXENT_ID
     *
     * @param wxentId the value for sys_user.WXENT_ID
     *
     * @mbggenerated
     */
    public void setWxentId(Long wxentId) {
        this.wxentId = wxentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.RECORD_STATUS
     *
     * @return the value of sys_user.RECORD_STATUS
     *
     * @mbggenerated
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.RECORD_STATUS
     *
     * @param recordStatus the value for sys_user.RECORD_STATUS
     *
     * @mbggenerated
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }
}